### ISSUE TITLE
Unable to dump slurm metrics since parse.py is returning empty dictionary 

### ISSUE THREAD

**Issue by blesson-james** [nsfcac/MonSter#3]
Getting below error while executing `mslurm.py`:
![image](https://user-images.githubusercontent.com/72782936/144606528-9d529794-29d7-41c8-97c6-5f5f8d1c6230.png)

The reason for above error is, `parse_node_metrics` method present in `parse.py` is returning empty dictionary. Please check the below screenshot:
![image](https://user-images.githubusercontent.com/72782936/144607034-0a46b2da-4b71-499e-a4bf-d127b80aa379.png)

The reason for the empty dictionary is, there is a if condition in `parse.py` where hostname from the response is compared with hostname present in `nodes` table which get the system hostname info from idrac using Redfish API in `idrac.py` as shown in the below screenshots:
![image](https://user-images.githubusercontent.com/72782936/144607544-00a67e30-ccf0-4dc1-a631-3a7413d4ecf6.png)
![image](https://user-images.githubusercontent.com/72782936/144607479-9dd06ab9-e576-4027-a950-3ba40f47feb2.png)

But usually our idrac system hostname & OS hostname will be different, due to which the scripts will fail everytime.

**Comment by Artlands** [comment]
> Getting below error while executing `mslurm.py`: ![image](https://user-images.githubusercontent.com/72782936/144606528-9d529794-29d7-41c8-97c6-5f5f8d1c6230.png)
> 
> The reason for above error is, `parse_node_metrics` method present in `parse.py` is returning empty dictionary. Please check the below screenshot: ![image](https://user-images.githubusercontent.com/72782936/144607034-0a46b2da-4b71-499e-a4bf-d127b80aa379.png)
> 
> The reason for the empty dictionary is, there is a if condition in `parse.py` where hostname from the response is compared with hostname present in `nodes` table which get the system hostname info from idrac using Redfish API in `idrac.py` as shown in the below screenshots: ![image](https://user-images.githubusercontent.com/72782936/144607544-00a67e30-ccf0-4dc1-a631-3a7413d4ecf6.png) ![image](https://user-images.githubusercontent.com/72782936/144607479-9dd06ab9-e576-4027-a950-3ba40f47feb2.png)
> 
> But usually our idrac system hostname & OS hostname will be different, due to which the scripts will fail everytime.

Thanks for reporting this issue. The hostname in the "nodes" table is obtained via iDRAC (/redfish/v1/Systems/System.Embedded.1), which is originally pulled from the node OS and is SUPPOSED to be aligned with the OS hostname. This is the hook where we correlate the Slurm info with iDRAC metrics. 

In the case that they are different, I will add configuration options in the config file, where the user can manually define the mapping of idrac hostnames to OS hostnames.
