### ISSUE TITLE
POST Request Blocked by CORS Policy

### ISSUE THREAD

**Issue by rinriko** [nsfcac/MonSter#4]
### Description:
I encountered an issue when attempting to make a POST request to the API endpoint https://hugo.hpcc.ttu.edu:5000/quanah from my client-side code running at http://127.0.0.1:5500. The request is being blocked by the CORS policy implemented on the server. However, I can download data directly from the API documentation (https://hugo.hpcc.ttu.edu:5000/docs#/default/main_quanah_post).

### Steps to Reproduce:

- Run client-side code from http://127.0.0.1:5500.
- Attempt to make a POST request to https://hugo.hpcc.ttu.edu:5000/quanah.
- Observe that the request is blocked by the CORS policy.

### Actual Behavior:
The request is blocked by the CORS policy, and I receive the following error message:
Access to fetch at 'https://hugo.hpcc.ttu.edu:5000/quanah' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

### Expected Behavior:
I expect to successfully make POST requests from the client-side to the API endpoint.

### Additional Information:

**Browser/Environment:** Google Chrome (Version 124.0.6367.62 (Official Build) (64-bit))
**Error Message:** Access to fetch at 'https://hugo.hpcc.ttu.edu:5000/quanah' from origin 'http://127.0.0.1:5500' has been blocked by **CORS policy:** Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
**Code Sample:** 

```
var url = 'https://hugo.hpcc.ttu.edu:5000/quanah';
    var postData = {
      start: "2024-02-20 12:00:00-06",
      end: "2024-02-20 14:00:00-06",
      interval: "5m",
      aggregation: "max",
      nodelist: "10.101.1.[1-60]",
      metrics: [
        "SystemPower_iDRAC",
        "NodeJobsCorrelation_Slurm",
        "JobsInfo_Slurm",
        "MemoryUsage_Slurm",
        "MemoryUsed_Slurm"
      ],
      compression: false
    };
    
d3.json(url, {
        method: 'POST',
        headers: {
          'accept': 'application/json',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(postData)
      })
      .then(data => {
        console.log(data); 
      })
      .catch(error => {
        console.error('There was a problem with the fetch operation:', error);
      });
```

**Screenshots:** 
![image](https://github.com/nsfcac/MonSter/assets/19527606/ea783f04-db73-42d8-b81e-a2e28ef505b8)

Thank you for your attention to this matter.

**Comment by BubbleMilkTea** [comment]
Thanks for reporting the issue, the issue you reported regarding the CORS policy should be resolved by the added cors configs under the branch name: `fix-cors-issue-4` 
Could you please test the functionality again on your end to ensure that the fix is working as expected?
Thank you again for bringing this to our attention.

**Comment by Artlands** [comment]
The bug is fixed in the latest update.
